config/routes.rb
Rails.application.routes.draw do
  resources :accreditation_school_lists
  resources :pmdk_school_lists
  resources :all_school_lists
  resources :address_kabupaten_lists
  resources :address_kecamatan_lists
  resources :address_province_lists
  resources :achievement_kategori_lists
  resources :achievement_tingkat_lists
  resources :source_motivation_lists
  resources :source_information_lists
  resources :batch_lists
  resources :organization_degree_lists
  resources :language_degree_lists
  resources :language_name_lists
  resources :extra_lists
  resources :personal_religion_lists
  resources :personal_gender_lists
  resources :parent_education_lists
  resources :parent_job_lists
  resources :high_school_majors
  resources :major_lists

  # get 'personals/new'
  # get 'personals/update'
  # get 'personals/edit'
  # get 'personals/show'
  # get 'personals/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get "/signup", to: 'users#new'
  #delete user by its id
  delete "users/:id", to: "users#destroy", as: :delete_user
  root "static_pages#home"
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  #show all registered users
  #get '/users', to: 'users#index'
  #add REST resources for users
  resources :users
  #handling sessions
  get '/login', to: 'sessions#new' #login page
  post 'login', to: 'sessions#create' #create the session
  #delete the session
  delete '/logout', to: 'sessions#destroy' #delete the session
  resources :users do #add following and followers action
    member do #member: get the user id
      get :following, :followers #get the following and followers,
      # url: /users/1/following and /users/1/followers,
      # named following_user_path(1) and followers_user_path(1)
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  #root "application#hello"
  # Defines the root path route ("/")
  # root "posts#index"
  #define as plural  if you have multiple data
  resources :account_activations,   only: [:edit]
  resources :password_resets,       only: [:edit, :new, :update, :create]
  resources :microposts,            only: [:create, :destroy]
  resources :relationships,         only: [:create, :destroy]
  resources :personals,             only: [:new, :create, :edit, :update, :show]
  resources :parents,               only: [:new, :create, :edit, :update, :show]
  resources :addresses,             only: [:new, :create, :edit, :update, :show]
  resources :languages,             only: [:new, :create, :edit, :update, :show]
  resources :achievements,          only: [:new, :create, :edit, :update, :show]
  resources :extras,                only: [:new, :create, :edit, :update, :show]
  resources :organizations,         only: [:new, :create, :edit, :update, :show]
  resources :sources,               only: [:new, :create, :edit, :update, :show]
  resources :majors,                only: [:new, :create, :edit, :update, :show]

  resources :pmdk_school_informations,      only: [:new, :create, :edit, :update, :show]
  resources :pmdk_each_score_informations,  only: [:new, :create, :edit, :update, :show]
  resources :pmdk_total_score_informations, only: [:new, :create, :edit, :update, :show]

  resources :utbk_scores,                 only: [:new, :create, :edit, :update, :show]
  resources :utbk_school_informations,    only: [:new, :create, :edit, :update, :show]
  resources :usm_school_informations,     only: [:new, :create, :edit, :update, :show]

end

app/models/parent_education_list.rb
class ParentEducationList < ApplicationRecord
  validates :pendidikan, presence: true, length: {minimum: 2, maximum: 20}, uniqueness: true
end

app/controllers/parent_education_lists_controller.rb
class ParentEducationListsController < ApplicationController
  before_action :set_parent_education_list, only: %i[ show edit update destroy ]

  # GET /parent_education_lists or /parent_education_lists.json
  def index
    @parent_education_lists = ParentEducationList.all
  end

  # GET /parent_education_lists/1 or /parent_education_lists/1.json
  def show
  end

  # GET /parent_education_lists/new
  def new
    @parent_education_list = ParentEducationList.new
  end

  # GET /parent_education_lists/1/edit
  def edit
  end

  # POST /parent_education_lists or /parent_education_lists.json
  def create
    @parent_education_list = ParentEducationList.new(parent_education_list_params)

    respond_to do |format|
      if @parent_education_list.save
        format.html { redirect_to parent_education_list_url(@parent_education_list), notice: "Parent education list was successfully created." }
        format.json { render :show, status: :created, location: @parent_education_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parent_education_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parent_education_lists/1 or /parent_education_lists/1.json
  def update
    respond_to do |format|
      if @parent_education_list.update(parent_education_list_params)
        format.html { redirect_to parent_education_list_url(@parent_education_list), notice: "Parent education list was successfully updated." }
        format.json { render :show, status: :ok, location: @parent_education_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parent_education_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parent_education_lists/1 or /parent_education_lists/1.json
  def destroy
    @parent_education_list.destroy!

    respond_to do |format|
      format.html { redirect_to parent_education_lists_url, notice: "Parent education list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent_education_list
      @parent_education_list = ParentEducationList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parent_education_list_params
      params.require(:parent_education_list).permit(:pendidikan)
    end
end

app/helpers/parent_education_lists_helper.rb
module ParentEducationListsHelper
end

app/views/parent_education_lists/_form.html.erb
<%= form_with(model: parent_education_list) do |form| %>
  <% if parent_education_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(parent_education_list.errors.count, "error") %> prohibited this parent_education_list from being saved:</h2>

      <ul>
        <% parent_education_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :pendidikan, style: "display: block" %>
    <%= form.text_field :pendidikan %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/parent_education_lists/_parent_education_list.html.erb
<div id="<%= dom_id parent_education_list %>">
  <p>
    <strong>Pendidikan:</strong>
    <%= parent_education_list.pendidikan %>
  </p>

</div>

app/views/parent_education_lists/edit.html.erb
<h1>Editing parent education list</h1>

<%= render "form", parent_education_list: @parent_education_list %>

<br>

<div>
  <%= link_to "Show this parent education list", @parent_education_list %> |
  <%= link_to "Back to parent education lists", parent_education_lists_path %>
</div>

app/views/parent_education_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Parent education lists</h1>

<div id="parent_education_lists">
  <% @parent_education_lists.each do |parent_education_list| %>
    <%= render parent_education_list %>
    <p>
      <%= link_to "Show this parent education list", parent_education_list %>
    </p>
  <% end %>
</div>

<%= link_to "New parent education list", new_parent_education_list_path %>

app/views/parent_education_lists/new.html.erb
<h1>New parent education list</h1>

<%= render "form", parent_education_list: @parent_education_list %>

<br>

<div>
  <%= link_to "Back to parent education lists", parent_education_lists_path %>
</div>

app/views/parent_education_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @parent_education_list %>

<div>
  <%= link_to "Edit this parent education list", edit_parent_education_list_path(@parent_education_list) %> |
  <%= link_to "Back to parent education lists", parent_education_lists_path %>

  <%= button_to "Destroy this parent education list", @parent_education_list, method: :delete %>
</div>