config/routes.rb
Rails.application.routes.draw do
  resources :accreditation_school_lists
  resources :pmdk_school_lists
  resources :all_school_lists
  resources :address_kabupaten_lists
  resources :address_kecamatan_lists
  resources :address_province_lists
  resources :achievement_kategori_lists
  resources :achievement_tingkat_lists
  resources :source_motivation_lists
  resources :source_information_lists
  resources :batch_lists
  resources :organization_degree_lists
  resources :language_degree_lists
  resources :language_name_lists
  resources :extra_lists
  resources :personal_religion_lists
  resources :personal_gender_lists
  resources :parent_education_lists
  resources :parent_job_lists
  resources :high_school_majors
  resources :major_lists

  # get 'personals/new'
  # get 'personals/update'
  # get 'personals/edit'
  # get 'personals/show'
  # get 'personals/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get "/signup", to: 'users#new'
  #delete user by its id
  delete "users/:id", to: "users#destroy", as: :delete_user
  root "static_pages#home"
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  #show all registered users
  #get '/users', to: 'users#index'
  #add REST resources for users
  resources :users
  #handling sessions
  get '/login', to: 'sessions#new' #login page
  post 'login', to: 'sessions#create' #create the session
  #delete the session
  delete '/logout', to: 'sessions#destroy' #delete the session
  resources :users do #add following and followers action
    member do #member: get the user id
      get :following, :followers #get the following and followers,
      # url: /users/1/following and /users/1/followers,
      # named following_user_path(1) and followers_user_path(1)
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  #root "application#hello"
  # Defines the root path route ("/")
  # root "posts#index"
  #define as plural  if you have multiple data
  resources :account_activations,   only: [:edit]
  resources :password_resets,       only: [:edit, :new, :update, :create]
  resources :microposts,            only: [:create, :destroy]
  resources :relationships,         only: [:create, :destroy]
  resources :personals,             only: [:new, :create, :edit, :update, :show]
  resources :parents,               only: [:new, :create, :edit, :update, :show]
  resources :addresses,             only: [:new, :create, :edit, :update, :show]
  resources :languages,             only: [:new, :create, :edit, :update, :show]
  resources :achievements,          only: [:new, :create, :edit, :update, :show]
  resources :extras,                only: [:new, :create, :edit, :update, :show]
  resources :organizations,         only: [:new, :create, :edit, :update, :show]
  resources :sources,               only: [:new, :create, :edit, :update, :show]
  resources :majors,                only: [:new, :create, :edit, :update, :show]

  resources :pmdk_school_informations,      only: [:new, :create, :edit, :update, :show]
  resources :pmdk_each_score_informations,  only: [:new, :create, :edit, :update, :show]
  resources :pmdk_total_score_informations, only: [:new, :create, :edit, :update, :show]

  resources :utbk_scores,                 only: [:new, :create, :edit, :update, :show]
  resources :utbk_school_informations,    only: [:new, :create, :edit, :update, :show]
  resources :usm_school_informations,     only: [:new, :create, :edit, :update, :show]

end

app/models/pmdk_school_list.rb
class PmdkSchoolList < ApplicationRecord
  validates :sekolah, presence: true,
            length: {minimum: 5, maximum: 35}, uniqueness: true
end

app/controllers/pmdk_school_lists_controller.rb
class PmdkSchoolListsController < ApplicationController
  before_action :set_pmdk_school_list, only: %i[ show edit update destroy ]

  # GET /pmdk_school_lists or /pmdk_school_lists.json
  def index
    @pmdk_school_lists = PmdkSchoolList.all
  end

  # GET /pmdk_school_lists/1 or /pmdk_school_lists/1.json
  def show
  end

  # GET /pmdk_school_lists/new
  def new
    @pmdk_school_list = PmdkSchoolList.new
  end

  # GET /pmdk_school_lists/1/edit
  def edit
  end

  # POST /pmdk_school_lists or /pmdk_school_lists.json
  def create
    @pmdk_school_list = PmdkSchoolList.new(pmdk_school_list_params)

    respond_to do |format|
      if @pmdk_school_list.save
        format.html { redirect_to pmdk_school_list_url(@pmdk_school_list), notice: "Pmdk school list was successfully created." }
        format.json { render :show, status: :created, location: @pmdk_school_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pmdk_school_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pmdk_school_lists/1 or /pmdk_school_lists/1.json
  def update
    respond_to do |format|
      if @pmdk_school_list.update(pmdk_school_list_params)
        format.html { redirect_to pmdk_school_list_url(@pmdk_school_list), notice: "Pmdk school list was successfully updated." }
        format.json { render :show, status: :ok, location: @pmdk_school_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pmdk_school_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pmdk_school_lists/1 or /pmdk_school_lists/1.json
  def destroy
    @pmdk_school_list.destroy!

    respond_to do |format|
      format.html { redirect_to pmdk_school_lists_url, notice: "Pmdk school list was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pmdk_school_list
      @pmdk_school_list = PmdkSchoolList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pmdk_school_list_params
      params.require(:pmdk_school_list).permit(:sekolah)
    end
end

app/helpers/pmdk_school_lists_helper.rb
module PmdkSchoolListsHelper
end

app/views/pmdk_school_lists/_form.html.erb
<%= form_with(model: pmdk_school_list) do |form| %>
  <% if pmdk_school_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pmdk_school_list.errors.count, "error") %> prohibited this pmdk_school_list from being saved:</h2>

      <ul>
        <% pmdk_school_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sekolah, style: "display: block" %>
    <%= form.text_field :sekolah %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pmdk_school_lists/_pmdk_school_list.html.erb
<div id="<%= dom_id pmdk_school_list %>">
  <p>
    <strong>Sekolah:</strong>
    <%= pmdk_school_list.sekolah %>
  </p>

</div>

app/views/pmdk_school_lists/edit.html.erb
<h1>Editing pmdk school list</h1>

<%= render "form", pmdk_school_list: @pmdk_school_list %>

<br>

<div>
  <%= link_to "Show this pmdk school list", @pmdk_school_list %> |
  <%= link_to "Back to pmdk school lists", pmdk_school_lists_path %>
</div>

app/views/pmdk_school_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pmdk school lists</h1>

<div id="pmdk_school_lists">
  <% @pmdk_school_lists.each do |pmdk_school_list| %>
    <%= render pmdk_school_list %>
    <p>
      <%= link_to "Show this pmdk school list", pmdk_school_list %>
    </p>
  <% end %>
</div>

<%= link_to "New pmdk school list", new_pmdk_school_list_path %>

app/views/pmdk_school_lists/new.html.erb
<h1>New pmdk school list</h1>

<%= render "form", pmdk_school_list: @pmdk_school_list %>

<br>

<div>
  <%= link_to "Back to pmdk school lists", pmdk_school_lists_path %>
</div>

app/views/pmdk_school_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pmdk_school_list %>

<div>
  <%= link_to "Edit this pmdk school list", edit_pmdk_school_list_path(@pmdk_school_list) %> |
  <%= link_to "Back to pmdk school lists", pmdk_school_lists_path %>

  <%= button_to "Destroy this pmdk school list", @pmdk_school_list, method: :delete %>
</div>